on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04 
    steps:
      - name: Install cppcheck
        run: apt update && apt install -y cppcheck

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run cppcheck
        run: cppcheck --error-exitcode=1 Core/